JavaEE_Project/src/java/model/Highscore.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Thomas
 */
@Entity
@Table(name = "Highscore")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Highscore.findAll", query = "SELECT h FROM Highscore h"),
    @NamedQuery(name = "Highscore.findById", query = "SELECT h FROM Highscore h WHERE h.id = :id"),
    @NamedQuery(name = "Highscore.findByName", query = "SELECT h FROM Highscore h WHERE h.name = :name"),
    @NamedQuery(name = "Highscore.orderedByName", query = "SELECT h FROM Highscore h ORDER BY h.name"),
    @NamedQuery(name = "Highscore.findByPoints", query = "SELECT h FROM Highscore h WHERE h.points = :points"),
    @NamedQuery(name = "Highscore.orderedByPoints", query = "SELECT h FROM Highscore h ORDER BY h.points DESC"),
    @NamedQuery(name = "Highscore.findByTimestamp", query = "SELECT h FROM Highscore h WHERE h.timestamp = :timestamp"),
    @NamedQuery(name = "Highscore.orderedByDate", query = "SELECT h FROM Highscore h ORDER BY h.timestamp DESC")})
public class Highscore implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "Name")
    private String name;
    @Basic(optional = false)
    @NotNull
    @Column(name = "Points")
    private int points;
    @Basic(optional = false)
    @NotNull
    @Column(name = "Timestamp")
    @Temporal(TemporalType.DATE)
    private Date timestamp;

    public Highscore() {
    }

    public Highscore(Integer id) {
        this.id = id;
    }

    public Highscore(Integer id, String name, int points, Date timestamp) {
        this.id = id;
        this.name = name;
        this.points = points;
        this.timestamp = timestamp;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPoints() {
        return points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Highscore)) {
            return false;
        }
        Highscore other = (Highscore) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "model.Highscore[ id=" + id + " ]";
    }

}

JavaEE_Project/src/java/controler/DataController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controler;

import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import model.Answers;
import model.Highscore;
import model.Questions;

/**
 *
 * @author Thomas
 */
@ManagedBean
@RequestScoped
public class DataController {

    @NotNull(message = "Question must be filled")
    @Pattern(regexp = "^[a-zA-Z0-9?.,_ ]*$", message = "Question contains non-alphabetic things")
    @Size(min = 5, max = 255, message = "Question to short or to long ")
    private String question;
    @Pattern(regexp = "^[a-zA-Z0-9_ ]*$", message = "Answer contains forbidden things")
    @Size(min = 5, max = 255, message = "Answer to short or to long ")
    @NotNull(message = "Answers must be filled")
    private String[] answers;
    private EntityManager em;
    private EntityTransaction t;
    private List<Highscore> scoreboard;

    /**
     * Creates a new instance of DataControler
     */
    public DataController() {
        em = Persistence.createEntityManagerFactory("JavaEE_ProjectPU").createEntityManager();
        this.scoreboard = em.createNamedQuery("Highscore.orderedByPoints").getResultList();
        answers = new String[4];
    }

    public List<Highscore> getScores() {
        return scoreboard;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String[] getAnswers() {
        return answers;
    }

    public void setAnswers(String[] answers) {
        this.answers = answers;
    }

    public void clear() {
        question = null;
        answers = new String[4];
    }

    public void sortByName() {
        this.scoreboard = em.createNamedQuery("Highscore.orderedByName").getResultList();
    }

    public void sortByDate() {
        this.scoreboard = em.createNamedQuery("Highscore.orderedByDate").getResultList();
    }

    public void addQuestion() {
        List<Answers> answerList = new LinkedList<>();
        Questions q = new Questions();
        q.setQuestion(question);
        doAnswers(q, answerList);
        t = em.getTransaction();
        t.begin();
        try {
            em.persist(q);
            t.commit();
        } catch (Exception e) {
            t.rollback();
        }
        clear();
    }

    private void doAnswers(Questions q, List<Answers> answerList) {
        Answers a = new Answers();
        a.setAnswer(answers[0]);
        a.setPoints(0);
        a.setQuestionID(q);
        answerList.add(a);
        a = new Answers();
        a.setAnswer(answers[1]);
        a.setPoints(3);
        a.setQuestionID(q);
        answerList.add(a);
        a = new Answers();
        a.setAnswer(answers[2]);
        a.setPoints(7);
        a.setQuestionID(q);
        answerList.add(a);
        a = new Answers();
        a.setAnswer(answers[3]);
        a.setPoints(15);
        a.setQuestionID(q);
        answerList.add(a);
        Collections.shuffle(answerList);
        q.setAnswersList(answerList);
    }

}

JavaEE_Project/src/java/controler/GameController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controler;

import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import model.Answers;
import model.Highscore;
import model.Questions;

/**
 *
 * @author Thomas
 */
@ManagedBean
@SessionScoped
public class GameController {

    private String name = "John Appleseed";
    private int roundCount = 0;
    private List<Questions> resultList;
    private Questions question;
    private Answers answerInGame;
    private int answerIndex;
    private EntityManager em;
    private EntityTransaction t;
    private int score = 0;

    /**
     * Creates a new instance of bean
     */
    public GameController() {
        em = Persistence.createEntityManagerFactory("JavaEE_ProjectPU").createEntityManager();
    }

    public String randomQuestions() {
        resultList = em.createNamedQuery("Questions.findAll").getResultList();
        Collections.shuffle(resultList);
        question = resultList.get(0);
        return "game";

    }

    public Questions getQuestion() {
        return question;
    }

    public void setQuestion(Questions question) {
        this.question = question;
    }

    public Answers getAnswerInGame() {
        return answerInGame;
    }

    public void setAnswerInGame(Answers answerInGame) {
        this.answerInGame = answerInGame;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAnswerIndex() {
        return answerIndex;
    }

    public void setAnswerIndex(int answerIndex) {
        this.answerIndex = answerIndex;
    }

    public String nextRound() {
        this.answerInGame = this.question.getAnswersList().get(this.answerIndex);
        if (this.roundCount < 10) {
            this.score += answerInGame.getPoints();
            this.roundCount++;
            this.answerInGame = null;
            if (this.roundCount < this.resultList.size()) {
                this.question = resultList.get(this.roundCount);
                return "game";
            }
        }
        this.persistScore();
        clear();
        return "highscore";
    }

    private void clear() {
        this.answerInGame = null;
        this.roundCount = 0;
        this.score = 0;
        this.logout();
    }

    public void logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
    }

    private void persistScore() {
        Highscore h = new Highscore();
        h.setName(name);
        h.setPoints(score);
        h.setTimestamp(new Date());
        t = em.getTransaction();
        t.begin();
        try {
            em.persist(h);
            t.commit();
        } catch (Exception e) {
            t.rollback();
        }

    }

}

JavaEE_Project/web/game.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>CountryBall Quiz !</title>
        <link rel="stylesheet" type="text/css" href="css/style.css"/>
    </h:head>
    <h:body>
        <header>
            <img src="image/header.png" alt="Header CountryBall Quiz" class="header-img"/>
            <h1>CountryBall Quiz</h1>
        </header>
        
        <h:form class="form-field">
            <h:outputText id="question1" class="question" value="#{gameController.question.question}"/>
            <h:selectOneRadio value="#{gameController.answerIndex}" class="radio-list">
                <f:selectItem itemValue="0" itemLabel="#{gameController.question.answersList.get(0).answer}" />
                <f:selectItem itemValue="1" itemLabel="#{gameController.question.answersList.get(1).answer}" />
                <f:selectItem itemValue="2" itemLabel="#{gameController.question.answersList.get(2).answer}" />
                <f:selectItem itemValue="3" itemLabel="#{gameController.question.answersList.get(3).answer}" />
            </h:selectOneRadio>
            <h:commandButton value="Send" action="#{gameController.nextRound}" class="send-form"/>
        </h:form>
    </h:body>
</html>

JavaEE_Project/web/gameName.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>CountryBall Quiz !</title>
        <link rel="stylesheet" type="text/css" href="css/style.css"/>
    </h:head>
    <h:body>
        <header>
            <img src="image/header.png" alt="Header CountryBall Quiz" class="header-img"/>
            <h1>CountryBall Quiz</h1>
        </header>
        
        <h:form class="form-field">
            <div class="first-q">
                <h:outputLabel value="Name of the player: "/>
                <h:inputText p:type="text" value="#{gameController.name}" />
            </div>
            <h:commandButton value="Send" action="#{gameController.randomQuestions()}" class="send-form"/>
        </h:form>
    </h:body>
</html>

JavaEE_Project/web/highscore.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>CountryBall Quiz !</title>
        <link rel="stylesheet" type="text/css" href="css/style.css"/>
    </h:head>
    <h:body>
        <header>
            <img src="image/header.png" alt="Header CountryBall Quiz" class="header-img"/>
            <h1>CountryBall Quiz</h1>
        </header>
        <h:form class="form-field">
            <h:commandButton value="Go Back" action="index.xhtml" class="send-form"/>
            <h:commandButton value="Sort by Name" action="#{dataController.sortByName}" class="send-form"/>
            <h:commandButton value="Sort by Date" action="#{dataController.sortByDate}" class="send-form"/>
            <h:dataTable value="#{dataController.scores}" var="item">
                <h:column><f:facet name="header">Name</f:facet>#{item.name}</h:column>
                <h:column><f:facet name="header">Points</f:facet>#{item.points}</h:column>
                <h:column><f:facet name="header">Date</f:facet><h:outputText value="#{item.timestamp}"> <f:convertDateTime type="date" pattern="d-M-yyyy"/> </h:outputText></h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>

JavaEE_Project/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>CountryBall Quiz !</title>
        <link rel="stylesheet" type="text/css" href="css/style.css"/>
    </h:head>
    <h:body>
        <header>
            <img src="image/header.png" alt="Header CountryBall Quiz" class="header-img"/>
            <h1>CountryBall Quiz</h1>
        </header>

        <h:form class="form-field">
            <h:commandButton value="Start Game" action="gameName.xhtml" class="send-form"/>
            <h:commandButton value="Submit Question" action="newQuestion.xhtml" class="send-form"/>
            <h:commandButton value="Show Highscore" action="highscore.xhtml" class="send-form"/>
        </h:form>
    </h:body>
</html>

JavaEE_Project/web/newQuestion.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>CountryBall Quiz !</title>
        <link rel="stylesheet" type="text/css" href="css/style.css"/>
    </h:head>
    <h:body>
        <f:view>
            <header>
                <img src="image/header.png" alt="Header CountryBall Quiz" class="header-img"/>
                <h1>CountryBall Quiz</h1>
            </header>
            <h:form class="form-field add-question">
                <div class="first-q">
                    <h:outputLabel value="New Question: "/>

                    <h:inputText p:type="text" value="#{dataController.question}" />
                </div>
                
                <div class="list-answer">
                    <div class="answer">
                        <h:outputLabel value="Answer 1, Points: 0 "/>
                        <h:inputText p:type="text" value="#{dataController.answers[0]}" />
                    </div>
                    <div class="answer">
                        <h:outputLabel  value="Answer 2, Points: 3 "/>
                        <h:inputText p:type="text" value="#{dataController.answers[1]}" />
                    </div>
                    <div class="answer">
                        <h:outputLabel value="Answer 3, Points: 7 "/>
                        <h:inputText p:type="text" value="#{dataController.answers[2]}" />
                    </div>
                    <div class="answer">
                        <h:outputLabel value="Answer 4, Points: 15"/>
                        <h:inputText p:type="text" value="#{dataController.answers[3]}" />
                    </div>
                </div>
                
                <h:commandButton value="Submit" action="#{dataController.addQuestion}" actionListener="index.html" class="send-form"/>
            </h:form>
            <h:form class="form-field"><h:commandButton value="Go Back" action="index.xhtml" class="send-form"/></h:form>
            
        </f:view>
    </h:body>
</html>